# Mengimport Library Tensorflow

In [1]:
import tensorflow as tf

# Buatlah sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor.

In [2]:
random_tensor = tf.random.normal([5,5])
random_tensor.numpy()

array([[-0.18888348, -1.3099947 , -0.22915761, -1.0444322 ,  0.42393595],
       [-0.5939381 ,  0.86279285, -1.0360916 ,  0.516751  ,  0.41945362],
       [-0.6103475 , -1.7207783 ,  1.7978761 ,  0.25052562, -0.92788976],
       [ 0.16212834, -0.37156075,  0.48100296, -0.0680768 , -0.42917976],
       [ 1.8875461 , -0.27881643,  0.67728835, -0.2821731 ,  0.32721034]],
      dtype=float32)

# Buatlah sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor.

In [15]:
prime_tensor = tf.convert_to_tensor([[1,3,5,7,11],
                                    [13, 17, 19, 23, 29], 
                                     [31, 37, 41, 43, 47], 
                                    [53, 59, 61, 67, 71], 
                                     [73, 79, 83, 89, 97]], dtype=tf.float32)
print(prime_tensor)

tf.Tensor(
[[ 1.  3.  5.  7. 11.]
 [13. 17. 19. 23. 29.]
 [31. 37. 41. 43. 47.]
 [53. 59. 61. 67. 71.]
 [73. 79. 83. 89. 97.]], shape=(5, 5), dtype=float32)


# Tampilkan dimensi dari kedua variable tersebut

In [16]:
print("Dimensi Variabel")
print("random_tensor Dimensi :",random_tensor.shape)
print("prime_tensor Dimensi :",prime_tensor.shape)

Dimensi Variabel
random_tensor Dimensi : (5, 5)
prime_tensor Dimensi : (5, 5)


# Tampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator).

In [21]:
#Penjumlahan
a = random_tensor
b = prime_tensor
tf.add(a,b)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 0.8111165,  1.6900053,  4.7708426,  5.955568 , 11.423936 ],
       [12.406062 , 17.862793 , 17.96391  , 23.51675  , 29.419453 ],
       [30.389652 , 35.27922  , 42.797874 , 43.250526 , 46.07211  ],
       [53.16213  , 58.62844  , 61.481003 , 66.93192  , 70.57082  ],
       [74.88754  , 78.72118  , 83.67729  , 88.71783  , 97.32721  ]],
      dtype=float32)>

In [25]:
#pengurangan
tf.subtract(a,b)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ -1.1888835,  -4.3099947,  -5.2291574,  -8.044432 , -10.576064 ],
       [-13.593938 , -16.137207 , -20.03609  , -22.48325  , -28.580547 ],
       [-31.610348 , -38.72078  , -39.202126 , -42.749474 , -47.92789  ],
       [-52.83787  , -59.37156  , -60.518997 , -67.06808  , -71.42918  ],
       [-71.11246  , -79.27882  , -82.32271  , -89.28217  , -96.67279  ]],
      dtype=float32)>

In [27]:
#perkalian
tf.multiply(a,b)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ -0.18888348,  -3.929984  ,  -1.1457881 ,  -7.311025  ,
          4.6632953 ],
       [ -7.721195  ,  14.667479  , -19.68574   ,  11.885273  ,
         12.164155  ],
       [-18.920773  , -63.6688    ,  73.71292   ,  10.772602  ,
        -43.61082   ],
       [  8.592802  , -21.922085  ,  29.34118   ,  -4.5611453 ,
        -30.471764  ],
       [137.79086   , -22.026499  ,  56.21493   , -25.113405  ,
         31.739403  ]], dtype=float32)>

In [28]:
#pembagian
tf.divide(a,b)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-0.18888348, -0.4366649 , -0.04583152, -0.1492046 ,  0.03853963],
       [-0.04568755,  0.05075252, -0.05453113,  0.02246743,  0.01446392],
       [-0.01968863, -0.04650752,  0.04385064,  0.00582618, -0.01974234],
       [ 0.00305903, -0.00629764,  0.00788529, -0.00101607, -0.00604479],
       [ 0.02585679, -0.00352932,  0.0081601 , -0.00317048,  0.0033733 ]],
      dtype=float32)>

In [29]:
tf.pow(a,b)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-1.8888348e-01, -2.2480638e+00, -6.3193357e-04, -1.3556939e+00,
         7.9488207e-05],
       [-1.1445520e-03,  8.1360035e-02, -1.9613930e+00,  2.5437259e-07,
         1.1424428e-11],
       [-2.2536811e-07, -5.2701443e+08,  2.7870857e+10,  1.4146288e-26,
        -2.9670853e-02],
       [ 0.0000000e+00, -4.2831194e-26,  4.0833115e-20, -0.0000000e+00,
        -8.2677122e-27],
       [ 1.3820437e+20, -0.0000000e+00,  8.9993143e-15, -0.0000000e+00,
         0.0000000e+00]], dtype=float32)>

# Tampilkan nilai maksimum dan minimum dari variable random_tensor.

In [31]:
argmax = tf.constant(random_tensor)
print("Nilai Maksimal random_tensor =",tf.argmax(random_tensor,axis=0))
print("Nilai Minimal random_tensor =",tf.argmin(random_tensor,axis=0))

Nilai Maksimal random_tensor = tf.Tensor([4 1 2 1 0], shape=(5,), dtype=int64)
Nilai Minimal random_tensor = tf.Tensor([2 2 1 0 2], shape=(5,), dtype=int64)


# Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [33]:
concat = tf.concat([random_tensor,prime_tensor], axis=0)
concat

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[-1.8888348e-01, -1.3099947e+00, -2.2915761e-01, -1.0444322e+00,
         4.2393595e-01],
       [-5.9393811e-01,  8.6279285e-01, -1.0360916e+00,  5.1675099e-01,
         4.1945362e-01],
       [-6.1034751e-01, -1.7207783e+00,  1.7978761e+00,  2.5052562e-01,
        -9.2788976e-01],
       [ 1.6212834e-01, -3.7156075e-01,  4.8100296e-01, -6.8076797e-02,
        -4.2917976e-01],
       [ 1.8875461e+00, -2.7881643e-01,  6.7728835e-01, -2.8217310e-01,
         3.2721034e-01],
       [ 1.0000000e+00,  3.0000000e+00,  5.0000000e+00,  7.0000000e+00,
         1.1000000e+01],
       [ 1.3000000e+01,  1.7000000e+01,  1.9000000e+01,  2.3000000e+01,
         2.9000000e+01],
       [ 3.1000000e+01,  3.7000000e+01,  4.1000000e+01,  4.3000000e+01,
         4.7000000e+01],
       [ 5.3000000e+01,  5.9000000e+01,  6.1000000e+01,  6.7000000e+01,
         7.1000000e+01],
       [ 7.3000000e+01,  7.9000000e+01,  8.3000000e+01,  8.9000000e+01,
      

# Tampilkan hasil sorting dari kedua variable di atas (descending)

In [36]:
print("Sorting random_tensor Descending")
print(tf.sort(random_tensor,direction="DESCENDING"))
print("\n")
print("Sorting prime_tensor Descending")
print(tf.sort(prime_tensor,direction="DESCENDING"))

Sorting random_tensor Descending
tf.Tensor(
[[ 0.42393595 -0.18888348 -0.22915761 -1.0444322  -1.3099947 ]
 [ 0.86279285  0.516751    0.41945362 -0.5939381  -1.0360916 ]
 [ 1.7978761   0.25052562 -0.6103475  -0.92788976 -1.7207783 ]
 [ 0.48100296  0.16212834 -0.0680768  -0.37156075 -0.42917976]
 [ 1.8875461   0.67728835  0.32721034 -0.27881643 -0.2821731 ]], shape=(5, 5), dtype=float32)


Sorting prime_tensor Descending
tf.Tensor(
[[11.  7.  5.  3.  1.]
 [29. 23. 19. 17. 13.]
 [47. 43. 41. 37. 31.]
 [71. 67. 61. 59. 53.]
 [97. 89. 83. 79. 73.]], shape=(5, 5), dtype=float32)
